name: nexe builds
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node:
          - 14
    runs-on: ${{ matrix.os }}

    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install nexe 
        run: npm i nexe -g

      - name: Install dependencies 
        run: npm install

      - name: Builds
        run: |
          nexe proxy-login-automator.js -t "linux-x64-14.15.3"
          nexe proxy-login-automator.js -t "windows-x64-14.15.3"
          nexe proxy-login-automator.js -t "mac-x64-14.15.3"